# shell prompt
PS1='\u@ \w\n$ '

# alias
alias ls='ls -G'
alias ll='ls -alh'
alias grep='grep --color'
alias tree='tree -N'
alias de='cd ~/Desktop'
alias code='open -b com.microsoft.VSCode "$@"'
alias atom='open -b com.github.atom "$@"'
alias serve='python -m SimpleHTTPServer "$@"'
alias convert-gb='iconv -f gb18030'

ss() {
    local SS_PROXY='http://localhost:1087'
    export http_proxy=$SS_PROXY
    export https_proxy=$SS_PROXY
    echo "Using Shadowsocks proxy: ${SS_PROXY}"
}
