" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'tpope/vim-sensible'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'


" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" Tab setting
set softtabstop=4 shiftwidth=4 expandtab